<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Каталог");
	
	$APPLICATION->IncludeComponent(
	"bitrix:catalog", 
	"catalog", 
	array(
		"COMPONENT_TEMPLATE" => "catalog",
		"IBLOCK_TYPE" => "#CATALOG_IBLOCK_TYPE#",
		"IBLOCK_ID" => "#CATALOG_IBLOCK_ID#",
		"DETAIL_USE_VOTE_RATING" => "N",
		"DETAIL_USE_COMMENTS" => "N",
		"DETAIL_BRAND_USE" => "N",
		"SIDEBAR_SECTION_SHOW" => "Y",
		"SIDEBAR_DETAIL_SHOW" => "Y",
		"SIDEBAR_PATH" => "",
		"SEF_MODE" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"CACHE_TYPE" => "N",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SET_TITLE" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_ELEMENT_CHAIN" => "Y",
		"USE_FILTER" => "Y",
		"FILTER_VIEW_MODE" => "VERTICAL",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"USE_COMPARE" => "Y",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"BASKET_URL" => "#SITE_DIR#cart/",
		"USE_PRODUCT_QUANTITY" => "Y",
		"PRODUCT_QUANTITY_VARIABLE" => "STARTSHOP_QUANTITY",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "Y",
		"PRODUCT_PROPERTIES" => array(
		),
		"SHOW_TOP_ELEMENTS" => "N",
		"TOP_ELEMENT_COUNT" => "9",
		"TOP_LINE_ELEMENT_COUNT" => "3",
		"TOP_ELEMENT_SORT_FIELD" => "sort",
		"TOP_ELEMENT_SORT_ORDER" => "asc",
		"TOP_ELEMENT_SORT_FIELD2" => "id",
		"TOP_ELEMENT_SORT_ORDER2" => "desc",
		"TOP_PROPERTY_CODE" => "",
		"TOP_VIEW_MODE" => "SECTION",
		"SECTION_COUNT_ELEMENTS" => "Y",
		"SECTION_TOP_DEPTH" => "2",
		"SECTIONS_VIEW_MODE" => "LIST",
		"SECTIONS_SHOW_PARENT_NAME" => "Y",
		"PAGE_ELEMENT_COUNT" => "32",
		"LINE_ELEMENT_COUNT" => "3",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER2" => "desc",
		"LIST_PROPERTY_CODE" => array(
			0 => "STARTSHOP_QUANTITY",
			1 => "STARTSHOP_QUANTITY_RATIO",
			2 => "SPECIALOFFER",
			3 => "PRICE",
			4 => "PRICECURRENCY",
			5 => "SIZE",
			6 => "S_SIZE",
			7 => "ARTNUMBER",
			8 => "MATERIAL",
			9 => "MANUFACTURER",
			10 => "",
		),
		"INCLUDE_SUBSECTIONS" => "N",
		"LIST_META_KEYWORDS" => "-",
		"LIST_META_DESCRIPTION" => "-",
		"LIST_BROWSER_TITLE" => "-",
		"SECTION_BACKGROUND_IMAGE" => "-",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "CML2_BRAND",
			1 => "reverse",
			2 => "ARTICLE",
			3 => "high",
			4 => "glubina",
			5 => "diagonal",
			6 => "notes",
			7 => "cam",
			8 => "kartrige",
			9 => "klass_stirki",
			10 => "SPECIALOFFER",
			11 => "PRICE",
			12 => "PRICECURRENCY",
			13 => "SIZE",
			14 => "S_SIZE",
			15 => "ARTNUMBER",
			16 => "MATERIAL",
			17 => "MANUFACTURER",
			18 => "",
		),
		"DETAIL_META_KEYWORDS" => "-",
		"DETAIL_META_DESCRIPTION" => "-",
		"DETAIL_BROWSER_TITLE" => "-",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
		"DETAIL_BACKGROUND_IMAGE" => "-",
		"SHOW_DEACTIVATED" => "N",
		"DETAIL_DISPLAY_NAME" => "Y",
		"DETAIL_DETAIL_PICTURE_MODE" => "IMG",
		"DETAIL_ADD_DETAIL_TO_SLIDER" => "N",
		"DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "E",
		"LINK_IBLOCK_TYPE" => "",
		"LINK_IBLOCK_ID" => "",
		"LINK_PROPERTY_SID" => "",
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
		"USE_STORE" => "Y",
		"PAGER_TEMPLATE" => "catalog",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Товары",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SET_STATUS_404" => "Y",
		"SHOW_404" => "Y",
		"MESSAGE_404" => "",
		"USE_ELEMENT_COUNTER" => "Y",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"REVIEWS_IBLOCK_TYPE" => "#REVIEWS_CATALOG_IBLOCK_TYPE#",
		"REVIEWS_IBLOCK_ID" => "#REVIEWS_CATALOG_IBLOCK_ID#",
		"GRID_CATALOG_ROOT_SECTIONS_COUNT" => "5",
		"GRID_CATALOG_SECTIONS_COUNT" => "3",
		"CURRENCY" => "",
		"ARTICLE_PROPERTY_CODE" => "",
		"MORE_PICTURES_CODE" => "",
		"CATALOG_MENU" => "catalog",
		"SHOW_LEFT_MENU_IN_ELEMENT" => "N",
		"FILTER_NAME" => "",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "CML2_BRAND",
			1 => "reverse",
			2 => "diagonal",
			3 => "power",
			4 => "os",
			5 => "country",
			6 => "",
		),
		"FILTER_PRICE_CODE" => array(
		),
		"SHOW_CUT_PROPS_ELEMENT" => "Y",
		"SHOW_CUT_PROPS_OF_ELEMENT" => "Y",
		"SHOW_SLIDER_IN_ELEMENT" => "Y",
		"SEF_FOLDER" => "#SITE_DIR#catalog/",
		"ADAPTABLE" => "Y",
		"USE_COMMON_CURRENCY" => "N",
		"PROPERTY_ARTICLE" => "ARTICLE",
		"PROPERTY_MORE_PICTURES" => "MORE_PICTURES",
		"FILE_404" => "",
		"PROPERTY_MORE_PICTURES_OFFERS" => "MORE_PHOTE",
		"COMPARE_NAME" => "CATALOG_COMPARE_LIST",
		"COMPARE_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"COMPARE_PROPERTY_CODE" => array(
			0 => "CML2_BRAND",
			1 => "STARTSHOP_QUANTITY_RATIO",
			2 => "power",
			3 => "os",
			4 => "supply",
			5 => "country",
			6 => "frontcamera",
			7 => "SPECIALOFFER",
			8 => "PRICE",
			9 => "PRICECURRENCY",
			10 => "SIZE",
			11 => "S_SIZE",
			12 => "ARTNUMBER",
			13 => "MATERIAL",
			14 => "MANUFACTURER",
			15 => "",
		),
		"COMPARE_ELEMENT_SORT_FIELD" => "sort",
		"COMPARE_ELEMENT_SORT_ORDER" => "asc",
		"DISPLAY_ELEMENT_SELECT_BOX" => "N",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"USE_REVIEW" => "Y",
		"SEF_URL_TEMPLATES" => array(
			"sections" => "",
			"section" => "#SECTION_CODE#/",
			"element" => "#SECTION_CODE#/#ELEMENT_ID#/",
			"compare" => "compare.php?action=#ACTION_CODE#",
			"smart_filter" => "#SECTION_ID#/filter/#SMART_FILTER_PATH#/apply/",
		),
		"CFO_USE_FASTORDER" => "Y",
		"OCB_USE_ONECLICKBUY" => "Y",
		"OCB_PROP_NAME" => "NAME",
		"OCB_PROP_PHONE" => "PHONE",
		"OCB_PHONE_COMMENT" => "COMMENT",
		"OCB_PROP_COMMENT" => "COMMENT",
		"VARIABLE_ALIASES" => array(
			"compare" => array(
				"ACTION_CODE" => "action",
			),
		)
	),
	false
	);
		
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>